[[https://github.com/tridactyl/tridactyl][Tridactyl]] is an amazing tool, offering amazing capabilities for a keyboard driven and predictable navigation in the browser. However there are many wonderful features that offer great customization possibilities which are not usually advertised or have easily available online examples. This repository exists to collect snippets with explanations for such features.


** Native Messenger and Exclaim Commands

   With the native messenger enabled, tridactyl can communicate directly with the system shell and execute arbitrary commands. This means you can run virtually run any commands using elements from the browser (such as the URL or selection) without breaking flow.

   *Warning*: This might have security risks (such as Remote Code Execution) and before using any of this snippets (or writing new ones along the lines), you should know what you are doing.

*** Youtube-dl
    - Download the auto generated subtiles of the current YouTube video.
    #+begin_src js
      bind yds composite js "\"" + document.location.href + "\"" | exclaim cd $HOME/Downloads/ && youtube-dl --write-auto-sub --skip-download
    #+end_src

    - Play the current YouTube link's audio in the background.
      TODO

    - Play the current YouTube video in a popup
    
    #+begin_src js
      bind Ypv js tri.native.run(`mpv --ytdl-format="[height <=? 480]" --ontop --geometry=20%x20% '${document.location.href}'`)
    #+end_src
    
      (Configure your Window Manager to set up the location of the window.)
